apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-bjkkff
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-bjkkff
    app.kubernetes.io/part-of: jvm-build-suite-application-gzcf
  name: jvm-build-suite-component-bjkkff
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-bjkkff
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-bjkkff
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-eyzi-tenant/jvm-build-suite-application-gzcf/jvm-build-suite-component-bjkkff@sha256:6f602014d41b561d50e7c5982a2b3073e00afe63ad6bf513dad3ceaebaef51f2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
